[workspace]

members = [
    "kvarko-cli",
    "kvarko-engine",
    "kvarko-lichess-bot",
    "kvarko-model",
    "kvarko-proc-macro",
    "kvarko-view"
]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1

[profile.test]
opt-level = 1
